# Multilingual
# 多语言，这里只设置中文
  [zh-cn]
    weight = 1
    languageCode = "zh-CN"
    languageName = "简体中文"
    hasCJKLanguage = true
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
    [zh-cn.menu]
      [[zh-cn.menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "经验帖"
        url = "/posts/"
        title = ""
      [[zh-cn.menu.main]]
        weight = 2
        identifier = "tags"
        pre = ""
        post = ""
        name = "标签"
        url = "/tags/"
        title = ""
      [[zh-cn.menu.main]]
        weight = 3
        identifier = "categories"
        pre = ""
        post = ""
        name = "分类"
        url = "/categories/"
        title = ""
      [[zh-cn.menu.main]]
        weight = 4
        identifier = "ref"
        pre = ""
        post = ""
        name = "准备&复习"
        url = "/ref/"
        title = ""
      [[zh-cn.menu.main]]
        weight = 5
        identifier = "guide"
        pre = ""
        post = ""
        name = "流程指引"
        url = "/guide/"
        title = ""
      [[zh-cn.menu.main]]
        weight = 6
        identifier = "about"
        pre = ""
        post = ""
        name = "关于"
        url = "/about/"
        title = ""
      [[zh-cn.menu.main]]
        weight = 7
        identifier = "github"
        pre = "<i class='fab fa-github fa-fw' aria-hidden='true'></i>"
        post = ""
        name = ""
        url = "https://github.com/jnu-baoyan"
        title = "GitHub"
    [zh-cn.params]
      [zh-cn.params.search]
        enable = false
        type = "algolia"
        contentLength = 4000
        placeholder = ""
        maxResultLength = 10
        snippetLength = 50
        highlightTag = "em"
        absoluteURL = false
        [zh-cn.params.search.algolia]
          index = ""
          appID = ""
          searchKey = ""
      [zh-cn.params.home]
        rss = 10
        [zh-cn.params.home.profile]
          enable = true
          gravatarEmail = ""
          
          # 添加封面小图片 
          avatarURL = "/images/lighthouse-small.jpg"
          title = "<span style='font-size: 1.8rem; font-weight: bold;'>江南大学 ME 保研经验仓库</span>"
          subtitle = "<span style='font-size: 1.2rem; font-weight: bold;'>那个夏天，我们顶峰相见</span>"
          typeit = true
          social = true
          disclaimer = ""
      [zh-cn.params.social]
        GitHub = "jnu-baoyan"
        Weibo = ""
        Steam = ""
        Zhihu = ""
        Douban = ""
        Devto = ""
        Bilibili = ""
        Email = "a2194037898@163.com"
        Phone = ""
        RSS = false